name: obslab
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - "./data:/etc/prometheus"
    networks:
      - obslab_reddit-network
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - obslab_reddit-network
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    volumes:
      - "./data/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro"
      - "./data/token.txt:/etc/alertmanager/token.txt:ro"
      - "./data/chat-id.txt:/etc/alertmanager/chat-id.txt:ro"
    networks:
      - obslab_reddit-network

networks:
  obslab_reddit-network:
    external: true